Feature/db handlers
PRD-ev/pyclub pull request #10
Opened 2018-10-09 09:25 UTC by tykazzz

2018-10-09 11:21 UTC, pniedzwiedzinski requested changes

2018-10-09 11:21 UTC, pniedzwiedzinski commented on pyclub/dbconnect.py
> +user = User(first_name='Maria')
To będzie wywalać błąd!

2018-10-09 11:21 UTC, pniedzwiedzinski commented on pyclub/dbconnect.py
> +def get_event_membership(membershipdata):
nic nie zwraca

2018-10-09 11:21 UTC, pniedzwiedzinski commented on pyclub/dbconnect.py
> +	c.execute('SELECT * FROM event_membership WHERE user_id=%s or event_id=%s or event_club_id=%s', (escape_string(membershipdata), escape_string(membershipdata), escape_string(membershipdata)))
to nie zadziała!!!!!

2018-10-09 11:21 UTC, pniedzwiedzinski commented on pyclub/dbconnect.py
> +def get_club_membership(membershipdata):
nic nie zwraca loool

2018-10-09 11:21 UTC, pniedzwiedzinski commented on pyclub/dbconnect.py
> +	c.execute('INSERT INTO user (email_confirm) values (1)')
to zadziała?

2018-10-09 14:08 UTC, butterfly-pn commented on pyclub/dbconnect.py
> +			  , (escape_string(first_name), escape_string(last_name), escape_string(email), escape_string(password))
Ta linijka jest za długa

2018-10-16 20:35 UTC, butterfly-pn commented on pyclub/dbconnect.py
> +	)
```suggestion
	)
```

2018-10-16 20:53 UTC, tykazzz commented on pyclub/dbconnect.py
> +def get_event_membership(membershipdata):
co nic nie zwraca?

2018-10-18 19:48 UTC, pniedzwiedzinski submitted a review, later dismissed

2018-10-23 21:01 UTC, pniedzwiedzinski requested changes

2018-10-23 21:01 UTC, pniedzwiedzinski commented on .gitignore
> +functions.txt
Wiem że to ten twój temp plik ale lepiej żeby nie było o nim mowy nigdzie w kodzie

2018-10-23 21:01 UTC, pniedzwiedzinski commented on pyclub/dbconnect.py
> +	'''Function connects to database'''
```suggestion
	"""Function connects to database"""
```
PEP

2018-10-23 21:01 UTC, pniedzwiedzinski commented on tests/test_database.py
> +def test_create_user():
Polecam sprawdzić pytest fixtures ;)

2018-10-25 20:44 UTC, pniedzwiedzinski requested changes

2018-10-25 20:44 UTC, butterfly-pn commented on api.py
> +def hello():
to już nie jest potrzebne

2018-10-25 20:44 UTC, butterfly-pn commented on api.py
> +def hi():
to już nie jest potrzebne

2018-10-25 20:44 UTC, butterfly-pn commented on pyclub/dbconnect.py
> +print(get_event_next_week())
```suggestion

```
lol

2018-10-25 20:45 UTC, butterfly-pn commented
Ej karamba! Część dbconnect jest na masterze!

2018-10-30 21:54 UTC, tykazzz commented on pyclub/dbconnect.py
> +	conn.commit()
@butterfly-pn gdzie tu jest trailing whitespace?

2018-11-20 10:31 UTC, pniedzwiedzinski submitted a review, later dismissed

2018-11-27 12:53 UTC, pniedzwiedzinski submitted a review, later dismissed

2018-11-28 22:37 UTC, pniedzwiedzinski approved these changes

2018-11-29 10:38 UTC, merged